#!/usr/bin/env sh
while read -r file
do
    case "$1" in
        "y")
            xclip -selection clipboard -t image/png "$file" &&
            notify-send "$file copied to clipboard" & ;;
    esac
done
