# Don't print a new line at the start of the prompt
# add_newline = false

[battery]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "
